### PR TITLE
Move genes into its own model

### PR DESCRIPTION
**Pull request by vsoch**
This is the expected PR to create a new genes module, moving everything from datasets over. To be conservative to test, I currently have the genes models pointing to still have the `datasets_` table prefix, and this way we don't have any migrations to do, e.g.,
```
$ python manage.py showmigrations --plan
Warning: connecting to production database.
[X]  contenttypes.0001_initial
[X]  auth.0001_initial
[X]  admin.0001_initial
[X]  admin.0002_logentry_remove_auto_add
[X]  admin.0003_logentry_add_action_flag_choices
[X]  contenttypes.0002_remove_content_type_name
[X]  auth.0002_alter_permission_name_max_length
[X]  auth.0003_alter_user_email_max_length
[X]  auth.0004_alter_user_username_opts
[X]  auth.0005_alter_user_last_login_null
[X]  auth.0006_require_contenttypes_0002
[X]  auth.0007_alter_validators_add_error_messages
[X]  auth.0008_alter_user_username_max_length
[X]  auth.0009_alter_user_last_name_max_length
[X]  auth.0010_alter_group_name_max_length
[X]  auth.0011_update_proxy_permissions
[X]  conditions.0001_initial
[X]  conditions.0002_auto_20201024_1938
[X]  phenotypes.0001_initial
[X]  papers.0001_initial
[X]  datasets.0001_initial
[X]  datasets.0002_gene
[X]  datasets.0003_data_gene
[X]  datasets.0004_datasetsimilarity_genesimilarity
[X]  datasets.0005_auto_20200903_2004
[X]  datasets.0006_auto_20200904_2323
[X]  datasets.0007_auto_20200912_1726
[X]  datasets.0008_auto_20200912_1854
[X]  datasets.0009_auto_20200913_0310
[X]  datasets.0010_auto_20200913_0312
[X]  datasets.0011_auto_20200921_2027
[X]  phenotypes.0002_remove_phenotype_observable2
[X]  phenotypes.0003_delete_observable2
[X]  sessions.0001_initial
```

I'm more nervous about doing the rename and then trying the migrations, so maybe @abarysh do you want to lead us through this? I can easily deploy this to staging with the current database since we don't have table changes, let me know if you want to do that first!

### CODE REVIEW

**Comment by vsoch** [comment]
@abarysh I also made a feeble attempt at adding a genes admin view, which you might want to tweak to your liking. I didn't test it fully because (of course) I forgot my password, which I'll figure out how to change/reset at some point :P

**Comment by abarysh** [comment]
It all looks good to me. It's a lot of changes, so probably hard to spot any bugs just by going through the code :) If you tested it locally and it behaves ok, let's deploy to staging and I'll test it more thoroughly there.

**Comment by vsoch** [comment]
I did test it thoroughly, but before the smaller changes/PRs were in. It's now deployed to staging - let me know after you've taken a look how you want to proceed. We could additionally try merging this branch with the current master and deploying that, and again to staging. And before we do any merging, we should again discuss if you want to do the table rename (and I'd make corresponding changes to the code).

**Comment by abarysh** [comment]
It looks great on staging right now. The only issue is on the admin side: I see the list of genes but can't access there edit pages (e.g., /admin/datasets/gene/6605/change/) -- server 500 error. This is not a big deal for now, I don't intend to be change any info about genes in the nearest future. So, I think the next step (as you suggested) would be to merge this into master and deploy to staging again, just to make sure it still works.

**Comment by vsoch** [comment]
I couldn't remember my password so I wasn't able to log in and test the (fairly random) test of the gene admin, so this is probably expected!

**Comment by vsoch** [comment]
I think we should deploy master into this branch, and then push to staging - both of which I can do locally and then we still have both separate branches here in case we need to step back.

**Comment by abarysh** [comment]
Sounds good, let’s do that!

**Comment by vsoch** [comment]
Ok - deployed to staging! I changed my password and fixed the Gene Admin views, so you should be able to see that too. When that looks good I have the commits ready to push here, and then we merge to master and deploy to production, and can start on the next round of bugs. :bug:  And also let me know if you still want to do the table renaming, and how we should go about that. It still makes me a bit anxious with migrations / messing something up, but if you've done it before and are fairly confident I will follow suite! :)

**Comment by abarysh** [comment]
Looks great! Let's deploy to production! In terms of table renaming, yeah, I've done it many times before. We can do this over the weekend (if that works for you), it should take at most a few minutes.

**Comment by vsoch** [comment]
Deployed to production! Also, the app engine costs look much better for the last two days, so if performance is okay this is a much better solution. But if performance is an issue and the only choice is to step up to the larger instance, if the costs increase to more than maybe $10/day we should probably re-consider compute engine.

**Comment by abarysh** [comment]
sounds great! performance has been good in my experience, I’ve used the
site several times throughout the day and never felt any delays.

**Pull request merged**
