### PR TITLE
many updates to search, etc

### PR DESCRIPTION
**Pull request by vsoch**
This PR fixes all but one issue addressed in an email from @abarysh - the remaining thing I need to do is represented in #57. Since this is quite a large amount of changes to look over via code, I'm going to deploy this to staging to make it easier to review (and will send an email with responses too!)

Signed-off-by: vsoch <vsochat@stanford.edu>

### CODE REVIEW

**Comment by vsoch** [comment]
Deployed to staging.

**Comment by vsoch** [comment]
Added page for tag "all" for a phenotype, will close #57 

image

Will update staging when tests pass.

**Comment by vsoch** [comment]
Deployed to staging - here is that same page https://staging-dot-calico-yeast-phenome-01.uc.r.appspot.com/phenotypes/tag/684/all.

**Comment by vsoch** [comment]
Deployed to staging.

**Comment by vsoch** [comment]
Deployed to staging!

**Comment by abarysh** [comment]
Look good to me!

**Comment by vsoch** [comment]
Deployed to production! I'm starting work on the next round of changes now, will open a new PR! There might be a little delay because I'm in the Science Slam this morning! http://www.stem-trek.org/2020/11/11/scienceslamsc20-saturday-nov-14-at-1100-a-m-central-gmt-6/

**Pull request merged**
