### PR TITLE
Admin updates

### PR DESCRIPTION
**Pull request by abarysh**
- Removed filter by conditiontype from condition search page
- Truncated the list of conditionset for conditions on search page
- Renamed a few methods in condition model for consistency

### CODE REVIEW

**Comment by vsoch** [comment]
@abarysh this looks good - the functions that are changed only appear where you changed them. Do you want to PR to #67, so we can merge into the single branch and I can deploy these changes to staging along with the index changes? I can also finish #67 with said changes, and then merge this after.

**Comment by abarysh** [comment]
Let's go with option 2 -- finish #67 and merge this after.

**Comment by vsoch** [comment]
@abarysh one tiny issue - this has the older commit (that was pushed, forced over) when I first changed to cornflower blue, so merging here now would undo all the recent changes, which we definitely don't want! Are you able to just grab the changes that you made in your commit to do a fresh PR? I think you should be able to update the branch with master, and if that doesn't do it, to checkout a new branch from master and then git cherry pick your commit. After this one is merged I can deploy to staging and production!

**Comment by abarysh** [comment]
Not sure if this will work: I fetched the upstream/master (your master), merged it into my master branch, then merged my master into my admin_update branch, and push all to my remote. I think this automatically updates this pull request. Am I understanding this right?

**Comment by vsoch** [comment]
Ah, almost! So I think what is happening here (why we are seeing old changes) is that your master wasn't in sync with upstream master (and maybe we ran into this before)?  If it were in sync, we'd only see the last two commits here (and not the others). The only commit we want is https://github.com/yeastphenome/yeastphenome.org/pull/68/commits/41cd3b7439b4275cbd2cf93418dde9f22673ce86. Let me see if there is an easy way to cherry pick it.

**Comment by vsoch** [comment]
Okay I was able to grab your commit, added via PR in #69! In the future you might want to be careful doing things with your remote master, because it looks like the commits are different, and this isn't your fault, it happens because we squash and merge here. If you want to start fresh, what you can do is clone the repository here, and then just change the origin to point to your origin (under abarysh) and then force push to abarysh/yeastphenome master and they should be in sync. And then always update from the master here.

**Pull request closed without merging**
