### PR TITLE
updates to datasets scores and similarities views

### PR DESCRIPTION
**Pull request by vsoch**
This PR will address issues related to the datasets phenotypic scores and similarity scores plots. Namely:

 - #112: removing the search genes box from datasets views and using the table filter for search
 - #113: making it easy to browse smaller bars with a mouseover that makes the entire column (regardless of the height) clickable.

Note that both issues reference views for `/genes/XXX/scores` and `/genes/XXX/similar`, however they should be referencing `/datasets/XXX/scores` and `/datasets/XXX/similar` as the genes views do not have plots yet. This would need to be addressed by #63, which has a dependency on the PR here.

Signed-off-by: vsoch <vsochat@stanford.edu>

### CODE REVIEW

**Comment by vsoch** [comment]
Deployed to staging.

**Comment by abarysh** [comment]
Looks great! I love the solution to #113! Just a couple of things that I think we should add right away:
1) We need a way to reset the selection somehow, i.e. to deselect a bar. It wasn't obvious to me how to do it. Intuitively, it seems to be that maybe clicking outside the plot should deselect the bar. Alternatively, a "Reset selection" link somewhere would also work.
2) We should label the x-axis on both plots ("Phenotypic scores" for `/datasets/XXX/scores` and "Correlation" for `/datasets/XXX/similar`) and add the y-axis ("Number of genes" for `/datasets/XXX/scores` and "Number of datasets" for `/datasets/XXX/similar`).

**Comment by vsoch** [comment]
Added reset buttons along with x and y xaxis labels, and deployed to staging.

Also, what do you think about changing the current discrete.html to just use quantiative.html? The view would look something like this:

image

instead of the current that just has bars all next to each other without giving a sense for where the values are. It would mean only one template to maintain instead of one each for discrete and quantitative. I think I originally created the two because some of the discrete plots looked off, but I can't find any I have issue with atm. I've deployed this change to staging if you want to see if you like it better.

Going for a run, back after.

**Comment by abarysh** [comment]
The axis labels look good, and I totally agree with the switch to quantitative template.

For the "Reset selection" button -- I'm not sure that's the best way to display it. Right now, the button feels disconnected from both the graph and the table -- it's always there, even if there's nothing selected, and therefore it's not clear what it's function is. What do you think about this? Make "Reset selection" appear as a link next to "Show [ 10] entries" only when the table is filtered (either from search or from selection on the graph). If we want to make it more obvious, we can make the "Reset selection" link to be red, same color as the selected bar.

Also, related to the color, do you think we could use the same color to indicate a selected bar and a selected row in the table? That will make the connection even more obvious. Right now, the selected bar is red but the selected row is bright yellow. I like the red, but it might be too bright for the table. So, maybe a lighter red for both?

**Comment by vsoch** [comment]
Updated, and deployed to staging.

**Comment by abarysh** [comment]
It looks perfect! 👍🏻 👍🏻 👍🏻  The position of the button is great, the color is perfect and it is very intuitive how it all works together. Ok to deploy to production!

**Comment by vsoch** [comment]
Deployed to production.

**Pull request merged**
