### PR TITLE
Abarysh/updates 20201209

### PR DESCRIPTION
**Pull request by vsoch**
This new PR combines the previous two, and I also tried again this morning to fix the ordering but had no luck.

### CODE REVIEW

**Comment by vsoch** [comment]
Deployed to staging.

**Comment by vsoch** [comment]
Changes deployed to staging.

**Comment by vsoch** [comment]
Deployed again to staging - redundant filters removed on explorer pages.

**Comment by abarysh** [comment]
Looks and works great! After we address issue #83, I think it's ok to merge and deploy to production.

**Comment by vsoch** [comment]
@abarysh we are deployed to staging with fixes to explorer searches! Do you want to take a look, and if all looks okay I'll merge and deploy to production? I'll also go through our current issues and close those that are resolved.

**Comment by abarysh** [comment]
Yep, I'll have a look in ~1 hour.

**Comment by vsoch** [comment]
okay, fix for #90 is deployed to staging.

**Comment by abarysh** [comment]
Ok, looks great. I think we're good to merge into master & deploy to production.

**Comment by vsoch** [comment]
Woohoo! I love this part. ;)

**Comment by vsoch** [comment]
Okay we're deployed for production! Tomorrow I'll go through our current issues carefully and close the ones that are resolved, follow up on those that aren't. And definitely open any new ones that you see fit!

**Comment by abarysh** [comment]
Great, thank you!

**Pull request merged**
