### PR TITLE
adding ability to download paperset list to paper admin

### PR DESCRIPTION
**Pull request by vsoch**
This pull request will add a button to download a list of datasets for a paper to the admin view, and remove it from the paper external view. Specifically, I had two options:

 - Figure out the javascript + model combined logic to generate the `Add additional <model>` row and thus add a button next to it
 - A simpler approach to add a custom row just to the Dataset Inline present in (what looks like) just the papers change form view.

The second is easier to see and figure out, and also wouldn't require further customizing the custom inline class so I opted for this approach. This means that for a paper with many datasets, we have a download button in a second row that looks like this:

image

And for a paper without datasets, it's not rendered.

image

The download button (working) is also restored. @abarysh is this an okay solution for #55? 
 
Signed-off-by: vsoch <vsochat@stanford.edu>

### CODE REVIEW

**Comment by abarysh** [comment]
Looks good to me! Anyway to not show the "+" sign next to "Download the list of datasets"? Either some other icon or no icon at all would be great. If it's too much work, no worries, it's not critical.

**Comment by vsoch** [comment]
Removed! I browsed through the admin icon set, and I didn't see any fit for a download. If we want to add one in the future it should be fairly easy, but I remembered you preferred simple (no icon) over icons, so I left it out for now:

image

**Comment by vsoch** [comment]
Deployed to staging! I double checked it, and can confirm the download button is present and working, and the link is gone from the user-facing interface. @abarysh let me know when you've had a look and I'll deploy to production.

**Comment by abarysh** [comment]
Staging test -- OK

**Comment by vsoch** [comment]
Production -- Deployed

**Pull request merged**
