### PR TITLE
Add/gene scatterplot

### PR DESCRIPTION
**Pull request by vsoch**
This will add a scatterplot to compare two genes. The link for viewing a scatterplot appears in the truncated similarity tables on the gene detail page, along with the larger "View all" table. For any pair: 

- We show a regression line along with the correlation.
- Mousing over a point shows the dataset id and coordinate (corresponding to the scores)
- clicking on a coordinate goes to the dataset page

Deployed to staging.

### CODE REVIEW

**Comment by abarysh** [comment]
Looks and works great! Here're a few adjustments:

- Mousing over should show the dataset name (not id). I know the dataset names are long and probably look a bit ugly, but we don't really have much choice for now -- the dataset id is meaningless to the user, so they have to click every time to figure out what dataset that is (which basically defeats the point of mousing over)
- If possible, let's remove the border around the dots -- it creates visual noise and doesn't add much.
- A regression line is not super-useful here (we don't always expect a linear relationship between data on the two axes). But it would be useful to draw an y=x diagonal line. Maybe in red, so that is stands out better? Could we also add a legend for the line ("y = x")
- I think that the URL can be simplified: /genes/1012/similar/5776/ (instead of /genes/1012/similar/scatterplot/5776/). This way we don't have to worry about the /genes/1012/similar/scatterplot/ page (which the user might end up at, if they try to navigate via the URL).
- The breadcrumbs navigation should follow the URL as well: Explore data > Genes > YHR045 / YHR045W > Similar genes > DAP1 / YPL170W
- The title should be "Phenotypic scores: YHR045W / YHR045W vs. DAP1 / YPL170W"
- It's really good to report the correlation value, but we should use the same format as on other pages: float with 2 decimal points +/- standard deviation (also float with 2 decimal points).

**Comment by vsoch** [comment]
All fixed. We don't have a standard deviation (we have a score and p value) so I could not add it. For the breadcrumb, since the last entry should be the present page (without a link), I flipped that with the second gene (so then links to both genes are provided). I also renamed the breadcrumb from "Similar Genes" to "Phenotypic Scores" since the breadcrumb is supposed to match the page title.

Deployed to staging.

**Comment by abarysh** [comment]
Yep, looking good. Just a couple more comments:
- Yes, the field in the model / database is called p-value, but it actually contains a standard deviation (and we're displaying it in the "Phenotypic Similarities" table for each gene (3rd column). We certainly need to rename the field, just didn't get there yet.
- I think it would be best to make the plot square. It will highlight both the relative and the absolute similarity between the 2 genes. "Square" here means: set the x and the y-axis limits to the same min and max, and make axes the same length, so that the red line is a true diagonal. For example, on genes/1012/similar/5776/ both axes should go from -17 to 9. To calculate the axis limits there're a couple of options. The easiest would be to set the left and the right extremes of both axes to the min and max of the data values (+ some margin as a percent of the min/max).
- Could we also make the dots slightly bigger so that it is easier to mouse over? It's possible that they'll start overlapping with one another, in which case -- could we try making them 50% transparent?
- Also, any chance that the text box that appears upon hovering can have a semi-transparent background? When I mouse over the dots in the middle of a cloud, it's a bit hard to read the text. We can either make the dots lighter (and the text bold?) or provide a light background for the text.
- For the breadcrumbs, I see your point but I think it may still be better to have <First gene> > Similar genes > <Second gene>. The path to the scatter plot page will (almost) always go through the "Similar genes" page (where we list all the genes similar to <First gene>) and that's where the user might want to go back. I agree that they might also want to visit the page corresponding to the <Second gene> and we may want to provide that link somewhere on the page as well. But I'm not sure that the breadcrumbs is the place to do that. To make the title be consistent with the breadcrumbs, we can change it to: "Genes similar to <First gene>: <Second gene>" (weird? confusing?)

**Comment by vsoch** [comment]
All set, again deployed to staging.

**Comment by abarysh** [comment]
Looks fantastic! Just one last change: can we make the title "Genes similar to XXX: YYY" (where XXX is the first gene, the one you started from, and YYY is the second gene). I realized that in my previous comment I used `<First gene>` and `<Second gene>` instead of XXX and YYY, but didn't mark them as code, so Github hid the text between the `<>` completely. Sorry about that! Feel free to deploy to production after that.

**Comment by vsoch** [comment]
How's that?

**Comment by abarysh** [comment]
It looks flipped to me: at https://staging-dot-calico-yeast-phenome-01.uc.r.appspot.com/genes/5776/similar/1012/ DAP1 is the first gene (the one I searched) and YHR045W is the second gene (the one I clicked on in the similarity table). So the title should be `Genes similar to DAP1 / YPL170W: YHR045W / YHR045W` (whereas currently the 2 genes are in the other order).

**Comment by vsoch** [comment]
The reason it's flipped is because the data is always going to present the gene scores in order of increasing ids (e.g., 1012 < 5776) and you can see the comment [here](https://github.com/yeastphenome/yeastphenome.org/pull/136/files#diff-bdf3b080ecf2a86f7c5a579e5f3395fc32acae0e27e32ff642861da9ae9d96a5R129). I wasn't sure how to arbitrarily enforce the ordering, or at least I was worried about flipping them by accident.

**Comment by vsoch** [comment]
I'll remove the ordering and you can see if it's better.

**Comment by abarysh** [comment]
Yeah, looking at the code I'm not sure I see why we would need to enforce the ordering (maybe I'm missing it?). It seems to me that a good convention is that gene1 (the one you started from) is on the x-axis and gene2 (the one you clicked on in the similarity table) is on the y-axis. Are there any cases where that wouldn't work?

**Comment by vsoch** [comment]
I think as long as this query always returns the data objects in the order of gene1 and then gene2, we should be okay:

```python
data = Data.objects.filter(
        Q(dataset_id__in=shared), Q(gene_id__in=[gene1.id, gene2.id])
)
```
My worry is that the order they came back in would be kind of random, in which case when we add the numbers to the list of data:
```python
    for value in values:
        if value[0] not in scores:
            scores[value[0]] = {
                "values": [],
                "genes": [],
                "names": [],
                "dataset_name": value[3],
            }
        scores[value[0]]["values"].append(value[2])
        scores[value[0]]["genes"].append(value[1])
        scores[value[0]]["names"].append(names[value[1]])
```
We would be adding potentially a gene2 first and calling it gene1. The "names" field in the data should always be correct since that is part of the query, but given that we treat the first value as gene1 and the second value as gene2, the question is whether our original gene1 and gene2 correspond. My impression is that the [order is not honored](https://stackoverflow.com/questions/5966462/sort-queryset-by-values-in-list). From testing it looked like the lower value always came first (gene1) which is why I enforced that above. The alternative would have been to, when looping through the data in the view, add an if statement that basically says "if the gene name corresponds to what we want for gene1, set it to x, otherwise set to y."

**Comment by abarysh** [comment]
I would recommend a slightly simpler strategy:

```
import pandas as pd

# Get data for gene1 as a pandas dataframe
data1 = pd.DataFrame(list(Data.objects.filter(gene_id=gene1.id).values()))

# Get data for gene2 as a pandas dataframe
data2 = pd.DataFrame(list(Data.objects.filter(gene_id=gene2.id).values()))

# Join the 2 dataframes using dataset_id as the key
data = data1.merge(data2, on='dataset_id')

# Only keep rows where both genes have values
data = data.loc[data['valuez_x'].notnull() & data['valuez_y'].notnull()]

# Get datasets names
datasets = pd.DataFrame(list(Dataset.objects.filter(id__in=data['dataset_id'].values).values()))

# Add them to the data dataframe
data = data.merge(datasets[['id','name']], left_on='dataset_id', right_on='id')

# Convert to dict (or any other format you need later on)
# This produces a dict of dicts:
# {'dataset_id': 1087, 'valuez_x': Decimal('-0.03625'), 'valuez_y': Decimal('-0.03010'), 'name': 'hom | growth (pooled culture) | benomyl [57.746 uM] | YPD + DMSO [2%] | Hoepfner D~Movva NR, 2014'}
values = data[['dataset_id','valuez_x','valuez_y','name']].to_dict(orient='index')
```

**Comment by abarysh** [comment]
Note: as I was looking into this, I noticed that some data in the `Data` table are duplicated. This is my fault (I have been working on reloading some data in the last month or so), I'll investigate now and figure out a solution. But for the time being, you might noticed that the pair dataset_id + gene_id might appear multiple times in the `Data` table (which should not be happening).

**Comment by vsoch** [comment]
Oh good thinking - pandas is good as this sort of thing! I'll test this locally.

**Comment by vsoch** [comment]
Tested, updated, and deployed to staging.

**Comment by abarysh** [comment]
Beautiful! Ok to deploy to production.

**Comment by abarysh** [comment]
Also: data duplication problem solved (might add an issue later to add a unique constraint on the dataset_id + gene_id pair in datasets_data).

**Comment by vsoch** [comment]
Deployed to production.

**Pull request merged**
