### PR TITLE
A few additional updates to ImprovedModelAdmin and django3 migrations

### PR DESCRIPTION
**Pull request by abarysh**

### CODE REVIEW

**Comment by abarysh** [comment]
If by any chance you end up looking at this tonight (Nov7), could you wait until tomorrow to update the app instance? I'm running a database-wide dataset name update and don't want to mess around with the connection to the DB. It will done in ~2 hours. Thanks!

**Comment by vsoch** [comment]
Sure, I’ll look at and review tomorrow!

**Review by vsoch — COMMENTED** [review]
This looks good to deploy to staging! If you want to talk about what you commented as a "hacky solution" we can at our next meeting - just superficially I'm thinking that it's a temporary fix to avoid adding everything to the lookup?

My one critique is that I don't think we should remove migrations - it is the case that the current database wouldn't need them again, but generally I think it's good practice to maintain a history of them, in case we needed to start from scratch. They all have dependencies on one another, so it's not removing an independent thing. If you need to run them again, you can just use `--fake`. From experience, I've had more negative experiences not keeping them and needing to re-generate and then getting errors. So, it it doesn't hurt to keep them, I think maybe we should? I can add them back for you after merge, or I can send them over via some other method (e.g., email). Let me know your thoughts!

**Comment by abarysh** [comment]
Re: migrations -- I wouldn't mind keeping them around, but in this particular case it adds an additional dependency for us: the mptt package. The main reason I removed them is that I don't have mptt installed in the env environment and `python manage.py runserver` was generating an error because mptt wasn't there. Is there a way to avoid installing mptt and yet get runserver to run locally?

**Comment by vsoch** [comment]
Let's think of ideas! What might easily work is to remove the import, and then change the two occurrences of the mptt fields, e.g.,:
```python
               (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="phenotypes.Observable2",
                    ),
                ),
```
to instead use a standard ForeignKey
```python
               (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="phenotypes.Observable2",
                    ),
                ),
```
They are just modified foreign keys, so the structure is otherwise the same, so it might just work! The other thing to try is to move the import into the Migration class. If Django is just importing the file (hence the import error) it would be able to do that. If it's actually processing the list (very likely) then this wouldn't work.

**Comment by abarysh** [comment]
Are you familiar with mptt? If you're sure that `mptt.fields.TreeForeignKey` is just a modified `ForeignKey`, then, yeah, it's worth a shot. In my experience, `mptt.fields.TreeForeignKey` are a bit more complicated. But maybe the extra functionality is not needed for migrations. In any case, feel free to try and see what works.

**Comment by vsoch** [comment]
Okay! If I'm hearing you right, I'll merge this and give a shot at adding them back with the change. Will give an update soon!

**Review by vsoch — APPROVED** [review]

**Comment by vsoch** [comment]
Okay, migrations are added back with removing mptt in #54, staging is deployed, and since the changes are tiny and I'm guessing you already tested locally, I deployed to production after taking a look myself.

**Pull request merged**
