### PR TITLE
fixing download buttons and disabling add when cart full

### PR DESCRIPTION
**Pull request by vsoch**
This pull request will address the following:

 - #102 adding Download now, Download all, in addition to "Add" across object views, and disabling add buttons when the cart is already full on page load.
 

Signed-off-by: vsoch <vsochat@stanford.edu>

### CODE REVIEW

**Comment by vsoch** [comment]
Deployed to staging.

**Comment by abarysh** [comment]
With certain window widths, the "Add all" button is not aligned to the "Add" buttons (see screenshot attached)
Screen Shot 2020-12-24 at 12 41 20 PM

**Comment by abarysh** [comment]
When pressing "Add all", the message (either about success or about exceeding cart capacity) appears at the top of the page again, not below "Datasets" where the user can see it. Also, this message doesn't disappear even if I remove some of the datasets from the cart. It seems to me that, if the message was below "Datasets", it would be updated at each subsequent action.

**Comment by abarysh** [comment]
After clicking "Download" in the Download Cart, the dataset table is cleared out, but the Download Metrics on the right still says "Total Datasets 30" (which was the number of datasets I was downloading) and the datasets table itself says "Showing 1 to 10 of 30 entries" and has 3 pages even if there're no entries in the table. It sounds to me that this page should be reset to the state you get when you click "Clear Downloads" manually.

**Comment by abarysh** [comment]
Clicking on the "Download now" button produced an "Error: Server Error" (tested with /papers/289/)

**Comment by abarysh** [comment]
The "Download now" button is labeled as "Download now" on papers and conditions, but as "Download all" on phenotypes, datasets and genes (it also has a different color on datasets and genes).

**Comment by abarysh** [comment]
Also, a minor point -- the text in the "Download now" (or "Download all") button doesn't seem to be centered with respect to the button (it looks too low to me -- see screenshot)
Screen Shot 2020-12-24 at 12 50 56 PM

**Comment by vsoch** [comment]
> With certain window widths, the "Add all" button is not aligned to the "Add" buttons (see screenshot attached)

I'll try aligning everything to the right.

> When pressing "Add all", the message (either about success or about exceeding cart capacity) appears at the top of the page again, not below "Datasets" where the user can see it. Also, this message doesn't disappear even if I remove some of the datasets from the cart. It seems to me that, if the message was below "Datasets", it would be updated at each subsequent action.

When the page refreshes, the scroll is again at the top, so the top is where the user would see it. These "Add all" views are done on the server (not from the browser, which wouldn't work because we would again update the session on the back end but not in the current rendered view). The messages are not dynamic to update from the table, but we can add a global clear command to the top message box when the user further interacts with datasets.

> Clicking on the "Download now" button produced an "Error: Server Error" (tested with /papers/289/)

I couldn't reproduce this locally, I'll try again after I deploy to staging.

> After clicking "Download" in the Download Cart, the dataset table is cleared out, but the Download Metrics on the right still says "Total Datasets 30" (which was the number of datasets I was downloading) and the datasets table itself says "Showing 1 to 10 of 30 entries" and has 3 pages even if there're no entries in the table. It sounds to me that this page should be reset to the state you get when you click "Clear Downloads" manually.

This is because we aren't actually changing the rendering of the page, it's just a hack to make the table look cleared. I'll add another hack to change the count to 0.

> The "Download now" button is labeled as "Download now" on papers and conditions, but as "Download all" on phenotypes, datasets and genes (it also has a different color on datasets and genes).

I'll rename all of them.

**Comment by abarysh** [comment]
>This is because we aren't actually changing the rendering of the page, it's just a hack to make the table look cleared. I'll add another hack to change the count to 0.

Instead of a hack, couldn't we just call the "Clear Download Cart" view after the download? I.e., imitate a manual click on "Clear Downloads"?

**Comment by vsoch** [comment]
Deployed to staging. The 500 error is memory related - there isn't enough to serialize the data for download.

> While handling this request, the process that handled this request was found to be using too much memory and was terminated. This is likely to cause a new process to be used for the next request to your application. If you see this message frequently, you may have a memory leak in your application or may be using an instance with insufficient memory. Consider setting a larger instance class in app.yaml.

**Comment by vsoch** [comment]
> Instead of a hack, couldn't we just call the "Clear Download Cart" view after the download? I.e., imitate a manual click on "Clear Downloads"?

This would be a page refresh, which would risk refreshing the page before the download is complete. I don't know of any reasonable way to do a callback for a download - for the loader and clearing the table I have a timeout function. If you have any ideas please test them out and let me know!

**Comment by abarysh** [comment]
> This would be a page refresh, which would risk refreshing the page before the download is complete. I don't know of any reasonable way to do a callback for a download - for the loader and clearing the table I have a timeout function. If you have any ideas please test them out and let me know!

Would this be an appropriate solution for us? https://stackoverflow.com/questions/50604257/download-file-and-redirect-in-a-response
```
$.fileDownload('some/file.pdf')
    .done(function () { window.location.href = 'REDIRECT_URL'; })
    .fail(function () { alert('File download failed!'); });
```

I guess the difference is that we don't have a file ready for download, but have to call a view to generate the file first. Do you think this would work as the following?

```
$.fileDownload({% url 'datasets:download_dataset_cart' %})
   .done(function () { window.location.href = {% url 'common:clear_cart' %} })
   .fail(function () { alert('File download failed!'); });
```

**Comment by vsoch** [comment]
This is an interesting plugin! It actually does something similar to what I was looking at for other downloads (before we fixed the function to be faster) to [use an iframe](https://github.com/johnculviner/jquery.fileDownload/blob/master/src/Scripts/jquery.fileDownload.js#L291) - and [here is what we have](https://github.com/yeastphenome/yeastphenome.org/blob/35b3beb1680cfe45ba61aa8dade5668282f22453/yeastphenome/apps/genes/templates/genes/similar_genes.html#L60). He figured out how to wrap it into ajax to have the nice control of running something when it's done or completed.

I tested it locally with the cart maxed out and it seems to work nicely, but the author himself seems to call this a [hack](https://github.com/johnculviner/jquery.fileDownload/issues/56#issuecomment-56715556). I want to double check this is okay with you? Sometimes developers use "hack" to mean more of a trick, and don't mean to say that it's not well thought out. Let me know what you think! Also note that it's important that the response headers include an extra cookie, otherwise the callbacks don't work.

I'm heading off to bet, but will be back tomorrow... err later today :)  The fix is deployed to staging.

**Comment by abarysh** [comment]
This looks good to me, ok to deploy to production whenever you're ready.

**Comment by vsoch** [comment]
Deployed to production. Overall much improvement, and there is still some subtle styling that makes the text slightly off center for some of the buttons, I'll take a look in the next round of work. 

image

**Comment by abarysh** [comment]
Sounds good

**Pull request merged**
