### PR TITLE
removing cart ratelimit and extra views

### LINKED ISSUE #95: Provide immediate feedback to user on adding to cart
Currently, for views that retrieve data with ajax (and don't refresh the page) we miss out on Django messages, and wind up with https://github.com/yeastphenome/yeastphenome.org/issues/76#issuecomment-743783115. We should have some strategy to be able to send back a message that can be used to update the page, even without reload.

### LINKED ISSUE #128: bug with download cart space
Given a few challenges with the "Add dataset to Download Cart" buttons, I am glad we have an opportunity to think about the Download feature as a whole. 

Currently, there're 4 ways to download data:
1. Download immediately the data you're looking at (for any given dataset or a gene)
2. Download immediately the data for all datasets in a table [not always available: yes at /phenotypes/587/; no at /conditions/4/]
3. Add a specific dataset to the Download Cart
4. Add all datasets in a table to the Download Cart [not always available: yes at /conditions/4/; no at /papers/289/]

[Option 5 will be available later on -- download all the data in the database in a single file.]

I think the order in which I listed the options also corresponds to their relative importance: option 1 is essential, 2 is important, 3 is nice to have and 4 is the cherry on top.

We can live perfectly fine with options 1 and 2 only, but options 3 and 4 (the download cart) are really useful and it would be great to keep them. However, we have to make sure they work robustly and consistently throughout the website.

My thoughts:
- if you feel that your current implementation (jquery) is not appropriate for our case, let's use a different one (e.g., react). I think it's worth the investment because patching an imperfect implementation wastes time in the long term.
- I think that we should keep the functionality as familiar for the user as possible. Adding something to the cart should be a 1-click action (using checkboxes and an "add all to cart" button would be 2 clicks).
- we currently have an inconsistency -- the cart only takes datasets, not genes. That's something to consider -- is there a relatively simple solution?
- minor point (probably captured by another issue): all dataset tables should have the same buttons (e.g., see option 2 example above) and these buttons should have the same name (e.g., /conditions/4/ says "Add all datasets to Downloads" whereas /phenotypes/587/ says "Add All to Download Later"). The buttons should just be part of the html template that has the datasets table.

### PR DESCRIPTION
**Pull request by vsoch**
This PR is more of a quick fix to ensure that the download cart doesn't bug out by having a ratelimit applied to the views. In addition, it looks like at some point the genes templates were re-added to the datasets view, so I'm removing them again. I started fixing up links (e.g., changing them from `<a><button></button></a>` but the work to update the download buttons is going to likely be significant and I don't want to hold up these changes waiting for it. Specifically this PR:

 - fixes #128: the cart had a weird bug that is resolved here
 - fixes #95: messages about adding/removing / full cart are now shown to the user
 
And although I started working on #102 to change buttons/a tags, the work that I think will be required there to update all views is substantial and I don't want to hold back the fixes here.

Signed-off-by: vsoch <vsochat@stanford.edu>

### CODE REVIEW

**Comment by vsoch** [comment]
Deployed to staging.

**Comment by abarysh** [comment]
Now that we've identified the source of the previous bug, do you think we could remove the temporary disabling of the "Add" button that was added to prevent multiple fast clicks? It just looks weird: you click on "Add" and you see the "disabled" sign (crossed circle) for a sec before it turns to "Remove". Since it's no longer necessary, I think we should remove it.

**Comment by vsoch** [comment]
I actually think it's still important - if you remove it and click *really* fast the button starts to flash. That wasn't related to the rate limit, that was just too many requests at once.

**Comment by abarysh** [comment]
Is flashing a problem? I.e., does it break the button and/or the rest of the page? Not sure if i'm imagining correctly, but in some way, that's the way it's supposed to be: if you have something that changes color at every click and you click really fast, that something will be flashing colors. The question is: does it stop when you stop clicking? or does it permanently break something?

**Comment by vsoch** [comment]
I guess not, I'll just remove disabling.

**Comment by vsoch** [comment]
Deployed to staging.

**Comment by abarysh** [comment]
Looks good to me, ok to deploy to production

**Comment by vsoch** [comment]
Deployed to production.

**Pull request merged**
