### PR TITLE
Db changes followup

### PR DESCRIPTION
**Pull request by abarysh**
Updates to Gene-related modes. Code refactoring to simplify, speed-up and/or just DRY.
PS: noticed that, despite my attempt to start fresh, this PR still has old commits... Need to discuss in more detail how to fix this (sorry for not being a github wiz yet).

### CODE REVIEW

**Comment by vsoch** [comment]
@abarysh it's your remote that you need to delete and re-create. If not that, then you'd need to do a force push to the main branch to override the old history. As long as you checkout a new branch from a master that has the old commits, and the commits aren't present in the upstream, they will show up.

I'll try again to fix it - we can't merge the old commits that delete needed files, and it makes me nervous what changes they might undo.

**Comment by abarysh** [comment]
Yep, makes sense. Just one quick question -- how come these old commits are not present in upstream? Is that something I didn't do correctly? My understanding is that the workflow is supposed to be the following:

Done once:
- Fork upstream to my own remote
- Clone my remote to local

Done every time:
- Create branch and commit changes to local
- Push branch to my remote
- Submit pull request from upstream

**Comment by vsoch** [comment]
The commits above are in your origin, here is one for example: https://github.com/abarysh/yeastphenome.org-1/commit/34a495081ed7c80f246878149093c2bdfec727c3

As an example, we can choose a commit in the list above `34a495081ed7c80f246878149093c2bdfec727c3
` - this commit is not present in upstream. You can see the commit was included in the PR here, https://github.com/yeastphenome/yeastphenome.org/pull/51 and then squashed to be a new commit https://github.com/yeastphenome/yeastphenome.org/commit/7ab42187f407748c9e1d8d3cfbe8fa0652bd3d5b.

**Comment by vsoch** [comment]
i can't seem to fix it like before, it always comes with the old commits. I think the safest thing to do is to look directly at commit https://github.com/yeastphenome/yeastphenome.org/pull/71/commits/eeb4141ce1a2b9823a12174f9b4e5c0b3b763b8e and then start with a clone of the upstream (yeastphenome/yeastphenome.org) and then make the changes again, or just open the entire files one by one and then copy the content verbatim. I don't feel comfortable just trying some kind of squash and merge and hoping nothing gets undone, and I haven't yet figured out any solution with git cherry pick or checkout of a commit. Sorry @abarysh :(

**Comment by abarysh** [comment]
No worries! I can totally do it, just need to think through it step by step. Give me a few min :)

**Comment by vsoch** [comment]
okay! Really sorry this is troublesome, for some reason I can't get the same fix to work with this tree as did with the last one. And to be more explicit (for next time) you would want to:

 - completely delete abarysh/yeastpheome-01, abarysh/yeastpheome
 - fork fresh to your account - this should ensure you have the same git history as upstream
 - clone the fork
 - `git checkout -b update/feature` checkout a new branch (never make changes on master!)
 - `git commit -a -s -m 'doing the updates'` commit and push
 - `git push origin updates/feature`
 - open a pull request from your fork `update/feature` to upstream master

Once those are merged, you checkout master on your fork, and pull from upstream master, and might as well update your remote as well.

```bash
git checkout master
git pull upstream master # ensure checking out a new branch has latest commits
git push origin master     # ensure git history in remote is synced
```
It's getting dark so I need to run, but I'll be back after!

**Comment by vsoch** [comment]
Added with #72

**Pull request closed without merging**
