### PR TITLE
Switched to genes_XXX tables. Added data_modified_on to datasets.

### PR DESCRIPTION
**Pull request by abarysh**

### CODE REVIEW

**Comment by vsoch** [comment]
Awesome! A few quick questions:

1. Did you test locally and see any messages about migrations (for the gene)
2. Have you done the migration to add the field - if yes, could we add the migration file, if no, how do you want to do it?

**Comment by abarysh** [comment]
1. Yes, tested locally, everything works as far as I can tell. I didn't look at migrations (I don't fully understand their inner workings, so I tend to avoid them).
2. Yes, the data_modified_on field already exists. Not sure what needs to be done on the migration side for this.

Let me know if I should do anything else.

**Comment by vsoch** [comment]
Ah okay - so you created the field manually? Then we wouldn't see a migration I don't think. If you've tested locally should we merge and then deploy to production?

**Comment by abarysh** [comment]
Shouldn't we deploy to staging first?

**Comment by vsoch** [comment]
Sure! I guess I could test it there along with locally.

**Comment by vsoch** [comment]
Deployed to staging, still seems to work!

**Comment by abarysh** [comment]
Yep, works for me too. Ok to deploy to production.

**Pull request merged**
