### PR TITLE
updates to navigation, datatables, and views

### PR DESCRIPTION
**Pull request by vsoch**
These are small tweaks to navigation and views per comments from last night! I'll be sending an email with more detail after opening this PR.

Signed-off-by: vsoch <vsochat@stanford.edu>

### CODE REVIEW

**Comment by vsoch** [comment]
Deployed to staging.

**Comment by vsoch** [comment]
Deployed to staging.

**Comment by vsoch** [comment]
Deployed to staging.

**Comment by vsoch** [comment]
Deployed to staging.

**Comment by vsoch** [comment]
Deployed to staging (does not include Comments (2020-11-18))

**Comment by vsoch** [comment]
Deployed to staging.

**Comment by vsoch** [comment]
Deployed to staging! When this is mostly good, do you want to merge and deploy to production soon @abarysh? The PR has been open for 9 days, and the site (on staging) is much better since!

**Comment by abarysh** [comment]
Yeah, I think it’s ok to deploy.

**Comment by vsoch** [comment]
Deployed to production.

**Pull request merged**
