### PR TITLE
fixing style and formatting of download buttons

### LINKED ISSUE #102: Improve consistency of Download buttons
Suggestion:

1. Buttons that add datasets to Download Cart should be named: 

- "Add" (when in the datasets table)
- "Add all to Download Cart" (when at the bottom of a datasets table)

2. Buttons that download data right away should be named:

- "Download now"

Question:

- What's best for capitalization? Our titles are all capitalized (e.g., "Phenotypic Scores for ..."). Should the buttons be, e.g., "Download now" or "Download Now"?

### PR DESCRIPTION
**Pull request by vsoch**
This should be the final fix for #102 - the download buttons are now consistent with the navigation links, namely with underlines for links, even spacing, and with all "Download now" primary blue and "View all" success green. This PR will close #102.

Signed-off-by: vsoch <vsochat@stanford.edu>

### CODE REVIEW

**Comment by vsoch** [comment]
Deployed to staging.

**Comment by abarysh** [comment]
Looks good. Just a couple of comments:
1. The "Download now" and "View all" buttons seem to have gotten smaller than the rest of the text. I noticed that the "button-sm" class was added to their style -- any particular reason for the change? It seems to me that the text size of the button label should be the same as the text everywhere else.
2. Should the "Add" and "Add all" buttons also have a similar style? I think they are the only buttons left without the change at this point.

**Comment by vsoch** [comment]
> The "Download now" and "View all" buttons seem to have gotten smaller than the rest of the text. I noticed that the "button-sm" class was added to their style -- any particular reason for the change? It seems to me that the text size of the button label should be the same as the text everywhere else.

Yes, these buttons now have the same class (btn-sm) and font size (12) as the other primary blue add to cart buttons. The main difference is that we have the added underline to match the style of the links in the navigation, and I've noticed this is your preference. The main difference is that the Add buttons don't have the underline, and they have a fixed width (whereas the download buttons have width that is specific to the text width).

> Should the "Add" and "Add all" buttons also have a similar style? I think they are the only buttons left without the change at this point.

I thought it looked nice in the table without the underline, but if this is your preference I can change it. Do you want flexible width along with just underline, or just underling? Note that if we do flexible width, the "Add" and "Add all" buttons will not be lined up as they are now.

**Comment by abarysh** [comment]
I think my preference would be to have all buttons look the same: underlined, flexible width and standard font size. Maybe it wasn't noticeable before with just the "Add" buttons, but now it is quite noticeable that "Download" and "View all" are substantially smaller than everything else, and something doesn't feel right about that. Can we make them all standard size (i.e., remove btn-sm)?

For the alignment and the "Add all" button -- I think we'll need to figure something else out. The alignment to the right doesn't look great (everything else is aligned to the left). Plus, the "Add all" button disappears when you switch to page 2 and others, and doesn't reappear after you switch back to page 1. I would be ok with removing the "Add all" button for now, until we get a better idea of where to put it and/or how to implement it.

**Comment by vsoch** [comment]
Okay, Add all buttons are removed, fixed widths are removed, and the "btn-sm" classes are removed, and deployed to staging.

For the future, note that when the "Add all" button is tried again the main issue is that we were using the `initComplete` callback instead of the [drawCallback](https://datatables.net/reference/option/drawCallback) to append the button after the table render. That is a separate issue from the spacing, however.

**Comment by abarysh** [comment]
Looks good to me. I would just revert the alignment of the "Add" buttons back to the left (just like all other columns in the datasets table are). Otherwise, good to deploy to production.

**Comment by abarysh** [comment]
Also forgot to mention -- would it be possible to set vertical alignment within the rows to  "center" instead of "top"? I'm looking at the datasets table on this page: https://staging-dot-calico-yeast-phenome-01.uc.r.appspot.com/papers/289/
It seems to me that a centered vertical alignment will look better.

**Comment by vsoch** [comment]
Vertical alignment is set to "middle" and the content is left-justified. Deployed to staging.

**Comment by abarysh** [comment]
Looks good! Ok to deploy to production.

**Comment by vsoch** [comment]
Deployed to production.

**Pull request merged**
