### PR TITLE
Hide scores for datasets without release permission

### PR DESCRIPTION
**Pull request by abarysh**
Sorry for one last minute update. For a handful of datasets (which I received directly from the authors) I am still waiting for explicit permission to release. Download is already disabled for these but viewing was still on. I just added a couple of if-statements to the templates to hide these data for now. It literally affects 2-3 papers at most. Could we merge this in before official release 1?

### CODE REVIEW

**Comment by vsoch** [comment]
Would you also want to hide them in dataset tables (e.g api/datasets.py, which has a datasets() function on several models and also uses datasets/search.py which right now does Datasets.all()?

**Comment by abarysh** [comment]
I don't think we have a problem showing that the datasets exist (that's public information). We just don't want the users to be able to see and/or download the actual data (phenotypic scores and similarities). This is a temporary restriction (and I'm sure can be implemented better later on).

**Comment by vsoch** [comment]
Ah, so we probably should disable the add to cart buttons in the server rendered table then?

**Comment by vsoch** [comment]
You could make a string set to disabled given the release variable and add to both buttons here: https://github.com/yeastphenome/yeastphenome.org/blob/8f8edae2b6dfeaa7a876b0b209af8f9fb1532c78/yeastphenome/apps/api/datasets.py#L112

I would also make sure a cart download filters these out first because someone could use the dataset id and add to cart endpoint to still add it!

**Comment by abarysh** [comment]
I have already disabled the download of these datasets in the download views a few PRs ago. So, currently, any attempt to download a forbidden dataset (directly or via Cart) results in a "Server 500" error. That's not ideal, but does the job :) The fraction of datasets not allowed for release is <1%, so I don't think the Server 500 error is a big deal in this case.

**Comment by vsoch** [comment]
So you are okay with the server error, and you want these changes merged and released to staging and production?

**Comment by abarysh** [comment]
Yes, thank you!

**Comment by vsoch** [comment]
Okay deployed to staging and production! One thing I noticed is that production had 3 instances running, likely because of the smaller size and running out of memory. For the other times (before we downsized) I would typically see just two.

**Comment by abarysh** [comment]
Yeah, that's possible. Although we're not doing any memory intensive stuff at the moment, just 2 users browsing pages, I assume. But let's monitor and see how it does performance-wise.

**Comment by vsoch** [comment]
When a download is done it saves it to "tmp" which is actually memory, so likely we want to disable this cache to maintain the smaller instance size.

**Comment by abarysh** [comment]
Yeah, I agree.

**Pull request merged**
