### PR TITLE
adding dataset/dataset scatterplot

### LINKED ISSUE #108: Add scatter plots to gene-gene and dataset-dataset similarity tables
The idea is to provide evidence for the correlation coefficient that we report for gene-gene pairs and dataset-dataset pairs. Ideally it would be something like this:
- in the all gene-gene similarity tables (the preview ones on the Gene detail page and the long ones on the /gene/XXX/similar/ page), we add one additional column with a link to "Scatter plot".
- when you click on the link, you're taken to a new page (located at /genes/XXX/similar/scatterplot/) that contains an interactive scatter plot of phenotypic scores for gene1 and gene2. Interactive here means that the user can hover over each dot and see the name of the dataset that corresponds to that dot.

Same thing for dataset-dataset pairs.

### LINKED ISSUE #137: Pubchem urls cannot have trailing slash
E.g., this URL works:

https://pubchem.ncbi.nlm.nih.gov/compound/5959

but this one give your a 404 error:

https://pubchem.ncbi.nlm.nih.gov/compound/5959/

### PR DESCRIPTION
**Pull request by vsoch**
This PR will add the datasets scatterplots. We use a shared template with the genes, and the biggest challenge is with respect to the titles - which are way larger than the axis and the header at the top. I used the ID where it absolutely was too large, and kept the dataset1 name in the title. I suspect we might need it somewhere else.

I stumbled on some plots that look off, for example: https://staging-dot-calico-yeast-phenome-01.uc.r.appspot.com/datasets/5568/similar/4930/

 - This will close #108 and will close #137 

Already deployed to staging.
 
Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by abarysh** [comment]
Looks good! 

For the dataset names: I think we should create a Dataset method (e.g., `short_name()`) that will create a truncated version of the dataset's name when needed (e.g., breadcrumbs navigation, plot axes etc.). Let's say we can handle 20 words (not 100% sure about the actual number) -- if the dataset's name is longer than that, short_name() can be the first 10 words + ' ... ' + the last 10 words. What do you think?

**Comment by vsoch** [comment]
All set (and deployed to staging). I tested a few of the longer names, and settled on 16 words, either using all or breaking into 8 and 8. I also made the `short_name` a property, since it seems appropriate.

**Comment by abarysh** [comment]
Looks great! ok to deploy to production

**Comment by vsoch** [comment]
Forgot to say - deployed to production (last night!)

**Pull request merged**
