### PR TITLE
fixing admin save, cannot return None

### PR DESCRIPTION
**Pull request by vsoch**
This pull request fixes two small bugs on the current staging server, specifically:

 - when we save a model, we have over-ridden the response_change function and need to run super() after checking for a popup, because if it's not that case, we are returning None (and the view needs a response).
 - the Componud.from_cid sometimes doesn't have synonyms, so we cannot index at 0.

@abarysh I wanted to ask you about the second case, because the one I was testing didn't have a synonym, but in the interface clearly had a value that must have come from somewhere?

Screenshot_2020-11-06 Change condition type Django site admin

I looked at the attributes on the comp result, and looking at other instances of ConditionType it looks like we are falling back to the comp.iupac_name (what I implemented here) however for this particular test case, I'm not sure where the value came from. We did change the pubmed_id from an int to a text field, so I tried retrieving the compound both ways (id as string and int) and the same thing is returned, so it's not that.

I think we have two options - either check for the synonym and fallback to the iupac_name, or check for the synonym and leave as None (don't add it) if it's not there.

Once this looks good, I'll merge and deploy to staging for you to preview! Then we can push to production when you give the signal.

Signed-off-by: vsoch <vsochat@stanford.edu>

### CODE REVIEW

**Comment by abarysh** [comment]
Looks good to me. For the Compound.from_id situation, I think your solution is correct. It's ok to fall back to iupac_name. The reason for the fact that we do have a synonym right now is that the Pubchem database is also evolving. Last time this compound was saved there was a synonym in Pubchem, and now it's no longer there. It's not a big deal for us, we can only link to other databases but we can't fix their behavior. Overall, I think we can go ahead with the merge.

**Comment by vsoch** [comment]
Deployed to staging!

**Comment by abarysh** [comment]
Staging OK!

**Comment by vsoch** [comment]
Deployed to production!

**Pull request merged**
